image: node:20-slim

variables:
  CI: "true"
  WRANGLER_SEND_METRICS: "false"
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn-cache"

cache:
  key: ${CI_COMMIT_REF_SLUG}-yarn
  paths:
    - .yarn-cache/
    - node_modules/

stages:
  - build
  - deploy

build_project:
  stage: build
  tags:
    - prd-runner
  script:
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

deploy_production:
  stage: deploy
  tags:
    - prd-runner
  environment:
    name: production
  only:
    - main
  dependencies:
    - build_project
  script:
    - echo "Deploying to Cloudflare Pages (production)..."
    - npx wrangler pages deploy dist
      --project-name=$CI_CF_PROJECT_SLUG
      --branch=$CI_COMMIT_REF_NAME
      --commit-dirty=true
  variables:
    CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN

deploy_development:
  stage: deploy
  tags:
    - dev-runner
  environment:
    name: development
  only:
    - development
  dependencies:
    - build_project
  script:
    - echo "Deploying to Cloudflare Pages (development)..."
    - yarn wrangler pages deploy dist
      --project-name=$CI_CF_PROJECT_SLUG
      --branch=$CI_COMMIT_REF_NAME
      --commit-dirty=true
  variables:
    CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
